name: build-documents

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    container: docker://metanorma/mn
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN || github.token }}
          submodules: true

      - uses: actions/cache@v2
        with:
          path: /config/fonts
          key: fontist-docker
          restore-keys: fontist-docker

      - run: curl -L --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/gemfile-to-bundle-add.sh | bash
        working-directory: ./src

      - run: metanorma site generate . -c collection.yml -o published --agree-to-terms
        working-directory: ./src

      - uses: actions/upload-artifact@v2
        with:
          name: published
          path: ./src/published

  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.METANORMA_CI_PAT_TOKEN || github.token }}
          submodules: true

      - uses: actions/download-artifact@v2
        with:
          name: published
          path: ./src/published

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_DEPLOY_KEY }}
          publish_dir: ./src/published
          force_orphan: true
          enable_jekyll: true
          user_name: ${{ github.actor }}
          user_email: ${{ format('{0}@users.noreply.github.com', github.actor) }}
          commit_message: "${{ format('Deploy to GitHub Pages: {0}', github.sha) }}"

      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 0
